---
# Check that webserver is up and webpage is updated

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Get http://localhost
      uri:
        url: http://localhost
        return_content: true
      register: http_response

    - name: Check nginx version
      assert:
        that: "http_response.server == 'nginx/1.19.10'"
        fail_msg: "Bummer: NGINX version must be 1.19.10. Current NGINX version is {{ http_response.server.split('/')[-1] }}"
        success_msg: "Good Work! NGINX version is 1.19.10"

    - name: Check nginx content
      assert:
        that: "'Hello, World!' in http_response.content"
        fail_msg: "Bummer: NGINX server response did not include \"Hello, World!\""
        success_msg: "Great Success!"
